intersections = [
    {
        "id": "villa - 1",
        "name": "Osmena St - Jocson St",
        "latitude": 10.688897,
        "longitude": 122.516400,
        "connections": ["villa - 2", "villa - 4", "villa - 6"],
    },
    {
        "id": "villa - 2",
        "name": "Iloilo Circumrferential Rd 1 - Jocson St",
        "latitude": 10.688957,
        "longitude": 122.521095,
        "connections": ["villa - 1", "villa - 3"],  # [3,4, Iloilo Circumferential Rd 1]
    },
    {
        "id": "villa - 3",
        "name": "Jocson St - Quezon St",
        "latitude": 10.688729,
        "longitude": 122.526827,
        "connections": ["villa - 2", "villa - 4", "Molo - 3"],
    },
    {
        "id": "villa - 4",
        "name": "Quezon St - Yulo Dr",
        "latitude": 10.687044,
        "longitude": 122.516604,
        "connections": ["villa - 1", "villa - 3"],
    },
    {
        "id": "villa - 5",
        "name": "Molo Blvd - Santa Cruz St",
        "latitude": 10.682915,
        "longitude": 122.494799,
        "connections": ["villa - 6", "Molo - 6"],
    },
    {
        "id": "villa - 6",
        "name": "Osmena St - Pakiad St",
        "latitude": 10.693689,
        "longitude": 122.498629,
        "connections": ["villa - 1", "villa - 7"],
    },
    {
        "id": "villa - 7",
        "name": "Pakiad Rd",
        "latitude": 10.694791,
        "longitude": 122.498790,
        "connections": ["villa - 6"],
    },
]

roads = [
    {
        "name": "Osmena St",
        "A": "villa - 1",
        "B": "villa - 6",
        "distance": 2000,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Molo Blvd",
        "A": "villa - 5",
        "B": "Molo - 6",
        "distance": 6600,
        "lanes": 1,
        "one_way": False,
    },
    {
        "name": "Yulo Dr",
        "A": "villa - 1",
        "B": "villa - 4",
        "distance": 200,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Quezon St",
        "A": "villa - 3",
        "B": "villa - 4",
        "distance": 1100,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Iloilo Circumferential Rd 1",
        "A": "villa - 2",
        "B": "mandurriao - 8",
        "distance": 2400,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Jocson St - Iloilo Circumferential Rd 1",
        "A": "villa - 1",
        "B": "villa - 2",
        "distance": 500,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Iloilo Circumferential Rd 1 - Jocson St",
        "A": "villa - 2",
        "B": "villa - 3",
        "distance": 650,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Pakiad Rd - Osmena St",
        "A": "villa - 7",
        "B": "villa - 6",
        "distance": 120,
        "lanes": 1,
        "one_way": False,
    },
]
