intersections = [
    {
        "id": "jaro - 1",
        "name": "E Lopez St - Luna St",
        "latitude": 10.715677,
        "longitude": 122.562659,
        "connections": ["jaro - 4", "lapaz - 3"],
    },
    {
        "id": "jaro - 2",
        "name": "Commission Civil St - Burgos St",
        "latitude": 10.717382,
        "longitude": 122.565081,
        "connections": ["jaro - 5", "lapaz - 7"],
    },
    {
        "id": "jaro - 3",
        "name": "Jereos St",
        "latitude": 10.719120,
        "longitude": 122.566883,
        "connections": ["lapaz - 6"],
    },
    {
        "id": "jaro - 4",
        "name": "Plaza Rizal St - E Lopez St",
        "latitude": 10.723266,
        "longitude": 122.557606,
        "connections": ["jaro - 1", "jaro - 5", "jaro - 7"],
    },
    {
        "id": "jaro - 5",
        "name": "Plaza Rizal St - Commission Civil St",
        "latitude": 10.724010,
        "longitude": 122.558338,
        "connections": ["jaro - 2", "jaro - 4", "jaro - 6"],
    },
    {
        "id": "jaro - 6",
        "name": "Plaza Rizal St - Iloilo-Capiz Rd/Lopez Jaena St",
        "latitude": 10.725553,
        "longitude": 122.557098,
        "connections": ["jaro - 5", "jaro - 7", "jaro - 8", "jaro - 9"],
    },
    {
        "id": "jaro - 7",
        "name": "Plaza Rizal St - El 98 St",
        "latitude": 10.724435,
        "longitude": 122.556176,
        "connections": ["jaro - 4", "jaro - 6", "mandurriao - 1"],
    },
    {
        "id": "jaro - 8",
        "name": "Iloilo-Capiz Rd - Lopez Jaena St",
        "latitude": 10.727475,
        "longitude": 122.555634,
        "connections": ["jaro - 6", "jaro - 9", "jaro - 18"],
    },
    {
        "id": "jaro - 9",
        "name": "Iloilo-Capiz Rd - Balabago Rd",
        "latitude": 10.730180,
        "longitude": 122.559115,
        "connections": ["jaro - 6", "jaro - 8", "jaro - 14", "jaro - 10"],
    },
    {
        "id": "jaro - 10",
        "name": "Balabago Rd - Iloilo Circumferential Rd 1",
        "latitude": 10.740585,
        "longitude": 122.582498,
        "connections": ["jaro - 9", "jaro - 11", "jaro - 12"],
    },
    {
        "id": "jaro - 11",
        "name": "Iloilo Circumferential Rd 1 - Monfort Blvd",
        "latitude": 10.740566,
        "longitude": 122.582805,
        "connections": ["jaro - 10", "jaro - 19", "jaro - 20"],
    },
    {
        "id": "jaro - 12",
        "name": "Buhang Flyover",
        "latitude": 10.749622,
        "longitude": 122.571865,
        "connections": ["jaro - 10", "jaro - 14"],
    },
    {
        "id": "jaro - 13",
        "name": "Buhang Flyover",
        "latitude": 10.750644,
        "longitude": 122.568030,
        "connections": ["jaro - 14", "jaro - 15"],
    },
    {
        "id": "jaro - 14",
        "name": "Iloilo-Capiz Rd - Iloilo Circumferential Rd 1",
        "latitude": 10.749916,
        "longitude": 122.569760,
        "connections": ["jaro - 9", "jaro - 12", "jaro - 13", "jaro - 21"],
    },
    {
        "id": "jaro - 15",
        "name": "Iloilo Circumferential Rd 1 - Iloilo Radial By-Pass Rd 4",
        "latitude": 10.753597,
        "longitude": 122.559114,
        "connections": ["jaro - 13", "jaro - 22", "jaro - 23"],
    },
    {
        "id": "jaro - 16",
        "name": "Old Lopez Jaena St - Old Iloilo-Capiz Rd",
        "latitude": 10.743941,
        "longitude": 122.539561,
        "connections": ["jaro - 17", "jaro - 18", "jaro - 24"],
    },
    {
        "id": "jaro - 17",
        "name": "Iloilo-Capiz Rd - Old Iloilo-Capiz Rd",
        "latitude": 10.742156,
        "longitude": 122.539263,
        "connections": ["jaro - 16", "jaro - 18"],
    },
    {
        "id": "jaro - 18",
        "name": "Old Lopez Jaena St - Iloilo-Capiz Rd",
        "latitude": 10.741662,
        "longitude": 122.540144,
        "connections": ["jaro - 16", "jaro - 17", "jaro - 8"],
    },
    {
        "id": "jaro - 19",
        "name": "Monfort Blvd",
        "latitude": 10.729156,
        "longitude": 122.579585,
        "connections": ["jaro - 11", "lapaz - 9"],
    },
    {
        "id": "jaro - 20",
        "name": "Coastal Rd - Leganes",
        "latitude": 10.765329,
        "longitude": 122.596838,
        "connections": ["jaro - 11"],
    },
    {
        "id": "jaro - 21",
        "name": "Iloilo R4 Rd - Leganes",
        "latitude": 10.776338,
        "longitude": 122.584777,
        "connections": ["jaro - 14"],
    },
    {
        "id": "jaro - 22",
        "name": "Iloilo Radial By-Pass Rd 4 - Leganes",
        "latitude": 10.782099,
        "longitude": 122.573353,
        "connections": ["jaro - 15"],
    },
    {
        "id": "jaro - 23",
        "name": "Iloilo Circumferential Rd 1 - Pavia",
        "latitude": 10.750579,
        "longitude": 122.540739,
        "connections": ["jaro - 15"],
    },
    {
        "id": "jaro - 24",
        "name": "Old Iloilo-Capiz Rd - Pavia",
        "latitude": 10.749019,
        "longitude": 122.539001,
        "connections": ["jaro - 16"],
    },
    {
        "id": "jaro - 25",
        "name": "Jereos St",
        "latitude": 10.720615,
        "longitude": 122.565701,
        "connections": ["jaro - 3"],
    },
]

roads = [
    {
        "name": "Monfort Blvd - Leganes",
        "A": "jaro - 11",
        "B": "jaro - 20",  # Dead End
        "distance": 3200,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Lapaz - Monfort Blvd",
        "A": "jaro - 19",
        "B": "jaro - 11",
        "distance": 1300,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Iloilo Circumferential - Iloilo Radial By-Pass Rd 4",
        "A": "jaro - 15",
        "B": "jaro - 22",  # Dead End
        "distance": 3500,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Iloilo Radial By-Pass Rd 4 - Buhang Flyover",
        "A": "jaro - 15",
        "B": "jaro - 13",
        "distance": 1100,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Buhang Flyover - Iloilo-Capiz Rd",
        "A": "jaro - 13",
        "B": "jaro - 14",
        "distance": 190,
        "lanes": 1,
        "one_way": False,
    },
    {
        "name": "Iloilo-Capiz Rd - Buhang Flyover",
        "A": "jaro - 14",
        "B": "jaro - 12",
        "distance": 220,
        "lanes": 1,
        "one_way": False,
    },
    {
        "name": "Buhang Flyover - Balabago Rd",
        "A": "jaro - 12",
        "B": "jaro - 10",
        "distance": 1600,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Iloilo-Capiz Rd - Iloilo Circumferential Rd 1 - Monfort Blvd",
        "A": "jaro - 10",
        "B": "jaro - 11",
        "distance": 35,
        "lanes": 1,
        "one_way": False,
    },
    {
        "name": "Old Iloilo-Capiz Rd - Iloilo-Capiz Rd",
        "A": "jaro - 17",
        "B": "mandurriao - 1",
        "distance": 3100,
        "lanes": 4,
        "one_way": False,
    },
    {
        "name": "Old Iloilo-Capiz Rd - Old Lopez Jaena St",
        "A": "jaro - 17",
        "B": "jaro - 16",
        "distance": 210,
        "lanes": 4,
        "one_way": False,
    },
    {
        "name": "Old Iloilo-Capiz Rd - Pavia",
        "A": "jaro - 16",
        "B": "jaro - 24",  # Dead End
        "distance": 550,
        "lanes": 4,
        "one_way": False,
    },
    {
        "name": "Iloilo-Capiz Rd - Iloilo Circumferential Rd 1",
        "A": "jaro - 14",
        "B": "jaro - 21",  # Dead End
        "distance": 3300,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Iloilo Radial By-Pass Rd 4",
        "A": "jaro - 15",
        "B": "jaro - 23",  # Dead End
        "distance": 3500,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Iloilo Capiz Rd - Balabago Rd",
        "A": "jaro - 14",
        "B": "jaro - 9",
        "distance": 2600,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Buhang Flyover",
        "A": "jaro - 12",
        "B": "jaro - 13",
        "distance": 450,
        "lanes": 1,
        "one_way": False,
    },
    {
        "name": "Balabago Rd",
        "A": "jaro - 9",
        "B": "jaro - 10",
        "distance": 2900,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Jereos St",
        "A": "jaro - 3",
        "B": "jaro - 25",  # Dead End
        "distance": 210,
        "lanes": 1,
        "one_way": False,
    },
    {
        "name": "Commission Civil St",
        "A": "jaro - 2",
        "B": "jaro - 5",
        "distance": 1000,
        "lanes": 1,
        "one_way": False,
    },
    {
        "name": "E Lopez St",
        "A": "jaro - 1",
        "B": "jaro - 4",
        "distance": 1000,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Plaza Rizal St - Balabago Rd",
        "A": "jaro - 6",
        "B": "jaro - 9",
        "distance": 550,
        "lanes": 1,
        "one_way": True,
    },
    {
        "name": "Iloilo-Capiz Rd - Lopez Jaena St",
        "A": "jaro - 9",
        "B": "jaro - 8",
        "distance": 500,
        "lanes": 2,
        "one_way": True,
    },
    {
        "name": "Lopez Jaena St - Plaza Rizal St",
        "A": "jaro - 8",
        "B": "jaro - 6",
        "distance": 260,
        "lanes": 3,
        "one_way": True,
    },
    {
        "name": "Lopez Jaena St - Old Lopez Jaena St",
        "A": "jaro - 8",
        "B": "jaro - 18",
        "distance": 2300,
        "lanes": 1,
        "one_way": False,
    },
    {
        "name": "Old Lopez Jaena St - Old Iloilo-Capiz Rd",
        "A": "jaro - 18",
        "B": "jaro - 17",
        "distance": 100,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Old Lopez Jaena St - Old Iloilo-Capiz Rd",
        "A": "jaro - 18",
        "B": "jaro - 16",
        "distance": 270,
        "lanes": 2,
        "one_way": True,
    },
    {
        "name": "El 98 St",
        "A": "jaro - 7",
        "B": "mandurriao - 1",
        "distance": 700,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "El 98 St - Plaza Rizal St - E Lopez St",
        "A": "jaro - 7",
        "B": "jaro - 4",
        "distance": 190,
        "lanes": 4,
        "one_way": True,
    },
    {
        "name": "E Lopez St - Plaza Rizal St - Commission Civil St",
        "A": "jaro - 4",
        "B": "jaro - 5",
        "distance": 120,
        "lanes": 4,
        "one_way": True,
    },
    {
        "name": "Commission Civil St - Plaza Rizal St - Iloilo-Capiz Rd",
        "A": "jaro - 5",
        "B": "jaro - 6",
        "distance": 230,
        "lanes": 4,
        "one_way": True,
    },
    {
        "name": "Iloilo-Capiz Rd - Plaza Rizal St - El 98 St",
        "A": "jaro - 6",
        "B": "jaro - 7",
        "distance": 160,
        "lanes": 5,
        "one_way": True,
    },
]
