intersections = [
    {
        "id": "lapaz - 1",
        "name": "Luna St - Huervana St",
        "latitude": 10.707804,
        "longitude": 122.567107,
        "connections": ["lapaz - 2", "lapaz - 3", "lapaz - 10"],
    },
    {
        "id": "lapaz- 2",
        "name": "Rizal St - Luna St",
        "latitude": 10.708378,
        "longitude": 122.567858,
        "connections": ["lapaz - 1", "lapaz - 3", "lapaz - 4"],
    },
    {
        "id": "lapaz - 3",
        "name": "Luna St - Luna St",
        "latitude": 10.709233,
        "longitude": 122.566694,
        "connections": ["lapaz - 1", "lapaz - 2", "jaro - 1"],
    },
    {
        "id": "lapaz - 4",
        "name": "Huervana St - Burgos St",
        "latitude": 10.710460,
        "longitude": 122.570379,
        "connections": ["lapaz - 2", "lapaz - 5", "lapaz - 7"],
    },
    {
        "id": "lapaz - 5",
        "name": "Huervana St - Jereos St",
        "latitude": 10.711606,
        "longitude": 122.571909,
        "connections": ["lapaz - 4", "lapaz - 6", "lapaz - 8"],
    },
    {
        "id": "lapaz - 6",
        "name": "Jereos St - Huervana Ext",
        "latitude": 10.713029,
        "longitude": 122.570879,
        "connections": ["lapaz - 5", "lapaz - 7", "jaro - 3"],
    },
    {
        "id": "lapaz - 7",
        "name": "Huervana Ext - Burgos St",
        "latitude": 10.711777,
        "longitude": 122.569511,
        "connections": ["lapaz - 4", "lapaz - 6", "jaro - 2"],
    },
    {
        "id": "lapaz - 8",
        "name": "Lopez Jaena St - Baldoza St",
        "latitude": 10.714306,
        "longitude": 122.575493,
        "connections": ["lapaz - 5", "lapaz - 9"],
    },
    {
        "id": "lapaz - 9",
        "name": "Baldoza St - Monfort Blvd",
        "latitude": 10.713908,
        "longitude": 122.581449,
        "connections": ["lapaz - 8", "lapuz - 7", "jaro - 19"],
    },
    {
        "id": "lapaz - 10",
        "name": "Luna St - Taytay Forbes",
        "latitude": 10.706364,
        "longitude": 122.567494,
        "connections": ["lapaz - 1"],  # [Bonifacio Dr, Lapuz]
    },
]

roads = [
    {
        "name": "Luna St",
        "A": "lapaz - 3",
        "B": "jaro - 1",  # E Lopez St
        "distance": 800,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Luna St - Huervana St",
        "A": "lapaz - 3",
        "B": "lapaz - 1",
        "distance": 170,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Luna St - Esplanade 5",
        "A": "lapaz - 1",
        "B": "lapaz - 10",
        "distance": 160,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Rizal St - Luna St",
        "A": "lapaz - 2",
        "B": "lapaz - 3",
        "distance": 160,
        "lanes": 4,
        "one_way": True,
    },
    {
        "name": "Huervana St - Rizal St",
        "A": "lapaz - 1",
        "B": "lapaz - 2",
        "distance": 110,
        "lanes": 4,
        "one_way": True,
    },
    {
        "name": "Huervana St - Burgos St",
        "A": "lapaz - 2",
        "B": "lapaz - 4",
        "distance": 350,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Huervana St - Jereos St",
        "A": "lapaz - 4",
        "B": "lapaz - 5",
        "distance": 210,
        "lanes": 4,
        "one_way": True,
    },
    {
        "name": "Jereos St - Huervana Ext",
        "A": "lapaz - 5",
        "B": "lapaz - 6",
        "distance": 200,
        "lanes": 4,
        "one_way": True,
    },
    {
        "name": "Huervana Ext",
        "A": "lapaz - 6",
        "B": "lapaz - 7",
        "distance": 210,
        "lanes": 3,
        "one_way": True,
    },
    {
        "name": "Burgos St - Huervana St",
        "A": "lapaz - 7",
        "B": "lapaz - 4",
        "distance": 180,
        "lanes": 4,
        "one_way": True,
    },
    {
        "name": "Lopez Jaena St",
        "A": "lapaz - 5",
        "B": "lapaz - 8",
        "distance": 500,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Baldoza St",
        "A": "lapaz - 8",
        "B": "lapaz - 9",
        "distance": 650,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Coastal Rd",
        "A": "lapaz - 9",
        "B": "lapuz - 7",
        "distance": 1200,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Monfort Blvd",
        "A": "lapaz - 9",
        "B": "jaro - 19",
        "distance": 1800,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Burgos St",
        "A": "lapaz - 7",
        "B": "jaro - 2",  # Commission Civil St
        "distance": 850,
        "lanes": 1,
        "one_way": False,
    },
    {
        "name": "Jereos St",
        "A": "lapaz - 6",
        "B": "jaro - 3",
        "distance": 600,
        "lanes": 1,
        "one_way": False,
    },
    {
        "name": "Divinagracia St",
        "A": "lapaz - 4",
        "B": "lapuz - 1",
        "distance": 450,
        "lanes": 1,
        "one_way": False,
    },
]
