intersections = [
    {
        "id": "lapuz - 1",
        "name": "Divinagracia St - Railroad St",
        "latitude": 10.707280,
        "longitude": 122.5715728,
        "connections": ["lapaz - 4", "lapuz - 3"],
    },
    {
        "id": "lapuz - 2",
        "name": "Rizal St - Quirino-Lopez Bridge",
        "latitude": 10.7022611,
        "longitude": 122.5714736,
        "connections": ["lapaz - 2", "lapuz - 4"], 
    },
    {
        "id": "lapuz - 3",
        "name": "Railroad St - Abanilla St",
        "latitude": 10.7031872,
        "longitude": 122.5739868,
        "connections": ["lapuz - 1"],
    },
    {
        "id": "lapuz - 4",
        "name": "Rizal St - New Iloilo Ferry Terminal Access Rd",
        "latitude": 10.7017752,
        "longitude": 122.5768179,
        "connections": ["lapuz - 4", "lapuz - 6"],
    },
    {
        "id": "lapuz - 5",
        "name": "New Iloilo Ferry Terminal Access Rd",
        "latitude": 10.697452,
        "longitude": 122.574277,
        "connections": ["lapuz - 4"],
    },
    {
        "id": "lapuz - 6",
        "name": "Rizal St - Lapuz-Mansaya-Roboc Rd",
        "latitude": 10.6985812,
        "longitude": 122.5820938,
        "connections": ["lapuz - 4", "lapuz - 8"],
    },
    {
        "id": "lapuz - 7",
        "name": "Lapuz-Mansaya-Roboc Rd - Coastal Rd",
        "latitude": 10.7060003,
        "longitude": 122.5887091,
        "connections": ["lapuz - 6", "lapaz - 9"],
    },
    {
        "id": "lapuz - 8",
        "name": "Lapuz-Mansaya-Roboc Rd",
        "latitude": 10.697268,
        "longitude": 122.583455,
        "connections": ["lapuz - 6"],
    },
]

roads = [
    {
        "name": "Railroad St",
        "A": "lapuz - 1",
        "B": "lapuz - 3",
        "distance": 550,
        "lanes": 1,
        "one_way": False,
    },
    {
        "name": "Rizal St - Huervana St",
        "A": "lapaz - 2",
        "B": "lapuz - 2",
        "distance": 850,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Rizal St - New Iloilo Ferry Terminal Access Rd",
        "A": "lapuz - 2",
        "B": "lapuz - 4",
        "distance": 600,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "New Iloilo Ferry Terminal Access Rd",
        "A": "lapuz - 4",
        "B": "lapuz - 5",
        "distance": 600,
        "lanes": 3,
        "one_way": False,
    },
    {
        "name": "Rizal St - Iloilo Airport Direct Rd",
        "A": "lapuz - 4",
        "B": "lapuz - 6",
        "distance": 700,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Lapuz Mansaya Loboc Rd",
        "A": "lapuz - 6",
        "B": "lapuz - 7",
        "distance": 1100,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Iloilo Airport Direct Rd",
        "A": "lapuz - 6",
        "B": "lapuz - 8",
        "distance": 240,
        "lanes": 1,
        "one_way": False,
    },
]
