intersections = [
    {
        "id": "mandurriao - 1",
        "name": "Mandurriao - Jaro Rd - Old Iloilo - Capiz Rd",
        "latitude": 10.719516,
        "longitude": 122.552187,
        "connections": ["mandurriao - 2", "jaro - 7", "jaro - 17"],
    },
    {
        "id": "mandurriao - 2",
        "name": "Mandurriao - Jaro Rd - Mandurriao - Sn Miguel Rd",
        "latitude": 10.717715,
        "longitude": 122.537628,
        "connections": ["mandurriao - 1", "mandurriao - 3", "mandurriao - 4"],
    },
    {
        "id": "mandurriao - 3",
        "name": "Mandurriao - Sn Miguel Rd - R Mapa St",
        "latitude": 10.719233,
        "longitude": 122.535611,
        "connections": ["mandurriao - 2", "mandurriao - 4"],
    },
    {
        "id": "mandurriao - 4",
        "name": "R Mapa St - Mandurriao - Jaro Rd",
        "latitude": 10.716513,
        "longitude": 122.536877,
        "connections": ["mandurriao - 2", "mandurriao - 3"],
    },
    {
        "id": "mandurriao - 5",
        "name": "Pakiad Rd",
        "latitude": 10.713336,
        "longitude": 122.523981,
        "connections": ["mandurriao  - 4"],
    },
    {
        "id": "mandurriao - 6",
        "name": "R Mapa St - Donato Pison Ave",
        "latitude": 10.704058,
        "longitude": 122.544081,
        "connections": ["mandurriao - 4", "mandurriao - 7"],
    },
    {
        "id": "mandurriao - 7",
        "name": "Tabucan Mandurriao",
        "latitude": 10.702897,
        "longitude": 122.545761,
        "connections": ["mandurriao - 6"],
    },
    {
        "id": "mandurriao - 8",
        "name": "Iloilo Circumferential Rd 1",
        "latitude": 10.708439,
        "longitude": 122.519555,
        "connections": ["villa - 2"],
    },
    {
        "id": "mandurriao - 9",
        "name": "Mandurriao-Sn Miguel Rd",
        "latitude": 10.740812,
        "longitude": 122.516723,
        "connections": ["mandurriao - 12"],
    },
    {
        "id": "mandurriao - 10",
        "name": "Iloilo Circumferential Rd 1 - Mandurriao-Sn Miguel Rd",
        "latitude": 10.737323,
        "longitude": 122.514159,
        "connections": ["mandurriao - 12"],
    },
    {
        "id": "mandurriao - 11",
        "name": "Mandurriao-Sn Miguel Rd - Iloilo Circumferential Rd 1",
        "latitude": 10.742752,
        "longitude": 122.519877,
        "connections": ["mandurriao - 12"],
    },
    {
        "id": "mandurriao - 12",
        "name": "Iloilo Circumferential Rd 1",
        "latitude": 10.740318,
        "longitude": 122.517041,
        "connections": [
            "mandurriao - 3",
            "mandurriao - 9",
            "mandurriao - 10",
            "mandurriao - 11",
        ],
    },
]

roads = [
    {
        "name": "Mandurriao - Sn Miguel Rd",
        "A": "mandurriao - 3",
        "B": "mandurriao - 12",
        "distance": 3100,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Pakiad Rd",
        "A": "mandurriao - 4",
        "B": "mandurriao - 5",
        "distance": 1600,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Old Iloilo - Capiz Rd",
        "A": "mandurriao - 1",
        "B": "Proper - 1", 
        "distance": 1100,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Mandurriao - Jaro Rd",
        "A": "mandurriao - 1",
        "B": "mandurriao - 2",
        "distance": 1100,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Mandurriao - Jaro Rd - Mandurriao - Sn Miguel Rd",
        "A": "mandurriao - 2",
        "B": "mandurriao - 3",
        "distance": 290,
        "lanes": 2,
        "one_way": True,
    },
    {
        "name": "Mandurriao - Sn Miguel Rd - R Mapa St",
        "A": "mandurriao - 3",
        "B": "mandurriao - 4",
        "distance": 350,
        "lanes": 4,
        "one_way": True,
    },
    {
        "name": "R Mapa St - Mandurriao - Jaro Rd",
        "A": "mandurriao - 4",
        "B": "mandurriao - 2",
        "distance": 170,
        "lanes": 2,
        "one_way": True,
    },
    {
        "name": "Mandurriao-Sn Miguel Rd - Iloilo Circumferential Rd 1",
        "A": "mandurriao - 9",
        "B": "mandurriao - 12",
        "distance": 65,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Iloilo Circumferential Rd 1 - Mandurriao-Sn Miguel Rd (1)",
        "A": "mandurriao - 10",
        "B": "mandurriao - 12",
        "distance": 450,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Iloilo Circumferential Rd 1 - Mandurriao-Sn Miguel Rd (2)",
        "A": "mandurriao - 11",
        "B": "mandurriao - 12",
        "distance": 400,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "R Mapa St",
        "A": "mandurriao - 4",
        "B": "mandurriao - 6",
        "distance": 1600,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "R Mapa St - Extension",
        "A": "mandurriao - 6",
        "B": "mandurriao - 7",
        "distance": 200,
        "lanes": 1,
        "one_way": False,
    },
]
