intersections = [
    # {
    #     "id": "Molo - 1",
    #     "name": "Locsin St - New Carpenter's Bridge",
    #     "latitude": 10.699186,
    #     "longitude": 122.542524,
    #     "connections": ["Molo - 2"],  # + connect outside sa molo
    # },
    # {
    #     "id": "Molo - 2",
    #     "name": "Locsin St - San Jose St.",
    #     "latitude": 10.698215,
    #     "longitude": 122.542886,
    #     "connections": ["Molo - 1", "Molo - 3"],
    # },
    {
        "id": "Molo - 3",
        "name": "Locsin St - San Marcos St.",
        "latitude": 10.697347,
        "longitude": 122.543396,
        "connections": ["Molo - 4", "villa - 3"],
    },
    {
        "id": "Molo - 4",
        "name": "Locsin St. - M.H Del Pilar St. 2",
        "latitude": 10.695993,
        "longitude": 122.544452,
        "connections": ["Molo - 3", "Molo - 5"],
    },
    {
        "id": "Molo - 5",
        "name": "Locsin St. - Timawa St.",
        "latitude": 10.694449,
        "longitude": 122.545638,
        "connections": ["Molo - 4", "Molo - 6", "Proper - 2"],
    },
    {
        "id": "Molo - 6",
        "name": "Locsin St. - Baluarte - Calumpag - Villa - Oton Blvd",
        "latitude": 10.692042,
        "longitude": 122.549359,
        "connections": ["Molo - 5", "Proper - 4"],
    },
    {
        "id": "Molo - 7",
        "name": "San Marcos St. - MH del Pilar St. 1 (Rotunda)",
        "latitude": 10.699246,
        "longitude": 122.549446,
        "connections": ["Molo - 3", "Proper - 1"],
    },
    {
        "id": "Molo - 8",
        "name": "San Marcos St. - MH del Pilar St. 1 (Rotunda)",
        "latitude": 10.699231,
        "longitude": 122.549295,
        "connections": ["Molo - 3", "Proper - 1"],
    },
    {
        "id": "Molo - 9",
        "name": "M.H Del Pilar St. 2",
        "latitude": 10.698880,
        "longitude": 122.549361,
        "connections": ["Molo - 4", "Proper - 1"],
    },
    {
        "id": "Molo - 10",
        "name": "M.H Del Pilar St. 2",
        "latitude": 10.698959,
        "longitude": 122.549522,
        "connections": ["Molo - 4", "Proper - 1"],
    },
]

roads = [
    # {
    #     "name": "Locsin St. 1",
    #     "A": "Molo - 1",
    #     "B": "Molo - 2",
    #     "distance": 120,
    #     "lanes": 2,
    #     "one_way": False,
    # },
    # {
    #     "name": "Locsin St. 2",
    #     "A": "Molo - 2",
    #     "B": "Molo - 3",
    #     "distance": 110,
    #     "lanes": 2,
    #     "one_way": False,
    # },
    {
        "name": "Molo - 3 -> Villa - 3",
        "A": "Molo - 3",
        "B": "villa - 3",
        "distance": 2100,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Molo - 3 -> Molo - 4",
        "A": "Molo - 3",
        "B": "Molo - 4",
        "distance": 190,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Molo - 4 -> Molo - 5",
        "A": "Molo - 4",
        "B": "Molo - 5",
        "distance": 220,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Molo - 4 -> Molo - 9",
        "A": "Molo - 4",
        "B": "Molo - 9",
        "distance": 650,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Molo - 5 -> Molo - 6",
        "A": "Molo - 5",
        "B": "Molo - 6",
        "distance": 500,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Molo - 7 -> Molo - 8",
        "A": "Molo - 7",
        "B": "Molo - 8",
        "distance": 16,
        "lanes": 2,
        "one_way": True,
    },
    {
        "name": "Molo - 8 -> Molo - 3",
        "A": "Molo - 8",
        "B": "Molo - 3",
        "distance": 700,
        "lanes": 4,
        "one_way": True,
    },
    {
        "name": "Molo - 8 -> Molo - 9",
        "A": "Molo - 8",
        "B": "Molo - 9",
        "distance": 42,
        "lanes": 1,
        "one_way": True,
    },
    {
        "name": "Molo - 9 -> Molo - 10",
        "A": "Molo - 9",
        "B": "Molo - 10",
        "distance": 20,
        "lanes": 4,
        "one_way": True,
    },
    {
        "name": "Molo - 10 -> Proper - 1",
        "A": "Molo - 10",
        "B": "Proper - 1",
        "distance": 500,
        "lanes": 2,
        "one_way": True,
    },
    {
        "name": "Molo - 10 -> Molo - 7",
        "A": "Molo - 10",
        "B": "Molo - 7",
        "distance": 38,
        "lanes": 1,
        "one_way": True,
    },
    {
        "name": "Proper - 1 -> Molo - 7",
        "A": "Proper - 1",
        "B": "Molo - 7",
        "distance": 550,
        "lanes": 4,
        "oneway": True,
    },
    {
        "name": "Molo Blvd 1",
        "A": "Molo - 6",
        "B": "villa - 5",
        "distance": 6600,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "New Carpenter Bridge",
        "A": "Molo - 3",
        "B": "mandurriao - 6",
        "distance": 800,
        "lanes": 1,
        "one_way": False,
    },
    {
        "name": "Timawa St",
        "A": "Molo - 5",
        "B": "Proper - 2",
        "distance": 1100,
        "lanes": 2,
        "one_way": False,
    },
    {
        "name": "Molo Blvd 2",
        "A": "Molo - 6",
        "B": "Proper - 4",
        "distance": 650,
        "lanes": 2,
        "one_way": False,
    },
]
