import csv

intersections = [
    # AREVALO / VILLA
    {
        "id": "villa - 1",
        "y": 10.688897,
        "x": 122.516400,
        "name": "Osmena St - Jocson St",
    },
    {
        "id": "villa - 2",
        "y": 10.688957,
        "x": 122.521095,
        "name": "Iloilo Circumrferential Rd 1 - Jocson St",
    },
    {
        "id": "villa - 3",
        "y": 10.688729,
        "x": 122.526827,
        "name": "Jocson St - Quezon St",
    },
    {"id": "villa - 4", "y": 10.687044, "x": 122.516604, "name": "Quezon St - Yulo Dr"},
    {
        "id": "villa - 5",
        "y": 10.682915,
        "x": 122.494799,
        "name": "Molo Blvd - Santa Cruz St",
    },
    {
        "id": "villa - 6",
        "y": 10.693689,
        "x": 122.498629,
        "name": "Osmena St - Pakiad St",
    },
    {"id": "villa - 7", "y": 10.694791, "x": 122.498790, "name": "Pakiad Rd"},
    # MOLO
    {
        "id": "Molo - 3",
        "y": 10.697347,
        "x": 122.543396,
        "name": "Locsin St - San Marcos St.",
    },
    {
        "id": "Molo - 4",
        "y": 10.695993,
        "x": 122.544452,
        "name": "Locsin St. - M.H Del Pilar St. 2",
    },
    {
        "id": "Molo - 5",
        "y": 10.694449,
        "x": 122.545638,
        "name": "Locsin St. - Timawa St.",
    },
    {
        "id": "Molo - 6",
        "y": 10.692042,
        "x": 122.549359,
        "name": "Locsin St. - Baluarte - Calumpag - Villa - Oton Blvd",
    },
    {
        "id": "Molo - 7",
        "y": 10.699246,
        "x": 122.549446,
        "name": "San Marcos St. - MH del Pilar St. 1 (Rotunda)",
    },
    {
        "id": "Molo - 8",
        "y": 10.699231,
        "x": 122.549295,
        "name": "San Marcos St. - MH del Pilar St. 1 (Rotunda)",
    },
    {"id": "Molo - 9", "y": 10.698880, "x": 122.549361, "name": "M.H Del Pilar St. 2"},
    {"id": "Molo - 10", "y": 10.698959, "x": 122.549522, "name": "M.H Del Pilar St. 2"},
    # CITY PROPER
    {
        "id": "Proper - 1",
        "y": 10.699766,
        "x": 122.554176,
        "name": "Gen Luna St - Infante St",
    },
    {
        "id": "Proper - 2",
        "y": 10.696536,
        "x": 122.554848,
        "name": "Delgado St - Infante St",
    },
    {
        "id": "Proper - 3",
        "y": 10.694484,
        "x": 122.555064,
        "name": "Rizal St - Infante St",
    },
    {
        "id": "Proper - 4",
        "y": 10.692782,
        "x": 122.555299,
        "name": "Baluarte - Calumpang - Villa - Oton Blvd - Infante St",
    },
    {
        "id": "Proper - 5",
        "y": 10.693734,
        "x": 122.556639,
        "name": "Baluarte - Calumpang - Villa - Oton Blvd - Rizal St",
    },
    {
        "id": "Proper - 6",
        "y": 10.693333,
        "x": 122.558918,
        "name": "Ledesma St - Rizal St",
    },
    {
        "id": "Proper - 7",
        "y": 10.701768,
        "x": 122.568323,
        "name": "Gen Luna St - Bonifacio Dr",
    },
    {
        "id": "Proper - 8",
        "y": 10.701513,
        "x": 122.569120,
        "name": "Gen Luna St - Ruperto Montinola St",
    },
    {
        "id": "Proper - 9",
        "y": 10.701726,
        "x": 122.569779,
        "name": "Gen Luna St - Muelle Loney St",
    },
    {
        "id": "Proper - 10",
        "y": 10.697813,
        "x": 122.569103,
        "name": "Delgado St - Ruperto Montinola St Left",
    },
    {
        "id": "Proper - 11",
        "y": 10.696552,
        "x": 122.569018,
        "name": "Ledesma St - Ruperto Montinola St",
    },
    {
        "id": "Proper - 12",
        "y": 10.697060,
        "x": 122.570971,
        "name": "Arroyo St - Muelle Loney St",
    },
    {
        "id": "Proper - 13",
        "y": 10.692725,
        "x": 122.572940,
        "name": "JM Basa St - De la Rama St",
    },
    {
        "id": "Proper - 14",
        "y": 10.691733,
        "x": 122.573801,
        "name": "JM Basa St - Rizal St",
    },
    {
        "id": "Proper - 15",
        "y": 10.689938,
        "x": 122.576432,
        "name": "General Hughes St - Duran St",
    },
    {"id": "Proper - 16", "y": 10.693996, "x": 122.579428, "name": "Duran St"},
    {
        "id": "Proper - 17",
        "y": 10.696937,
        "x": 122.577236,
        "name": "Dela Rama St - Blumentritt",
    },
    {
        "id": "Proper - 18",
        "y": 10.697315,
        "x": 122.575792,
        "name": "Muelle Loney St - Blumentritt Left",
    },
    {
        "id": "Proper - 19",
        "y": 10.696437,
        "x": 122.579052,
        "name": "Muelle Loney St - Blumentritt Right",
    },
    {"id": "Proper - 20", "y": 10.697963, "x": 122.578372, "name": "De la Rama St"},
    {
        "id": "Proper - 21",
        "y": 10.692842,
        "x": 122.582764,
        "name": "Fort San Pedro Dr - Muelle Loney St",
    },
    {
        "id": "Proper - 22",
        "y": 10.688291,
        "x": 122.579310,
        "name": "Fort San Pedro Dr - General Hughes St",
    },
    {
        "id": "Proper - 23",
        "y": 10.696552,
        "x": 122.569018,
        "name": "Arroyo St - Ruperto Montinola St",
    },
    {
        "id": "Proper - 24",
        "y": 10.697813,
        "x": 122.569103,
        "name": "Delgado St - Ruperto Montinola St Right",
    },
    # MANDURRIAO
    {
        "id": "mandurriao - 1",
        "y": 10.719516,
        "x": 122.552187,
        "name": "Mandurriao - Jaro Rd - Old Iloilo - Capiz Rd",
    },
    {
        "id": "mandurriao - 2",
        "y": 10.717715,
        "x": 122.537628,
        "name": "Mandurriao - Jaro Rd - Mandurriao - Sn Miguel Rd",
    },
    {
        "id": "mandurriao - 3",
        "y": 10.719233,
        "x": 122.535611,
        "name": "Mandurriao - Sn Miguel Rd - R Mapa St",
    },
    {
        "id": "mandurriao - 4",
        "y": 10.716513,
        "x": 122.536877,
        "name": "R Mapa St - Mandurriao - Jaro Rd",
    },
    {"id": "mandurriao - 5", "y": 10.713336, "x": 122.523981, "name": "Pakiad Rd"},
    {
        "id": "mandurriao - 6",
        "y": 10.704058,
        "x": 122.544081,
        "name": "R Mapa St - Donato Pison Ave",
    },
    {
        "id": "mandurriao - 7",
        "y": 10.702897,
        "x": 122.545761,
        "name": "Tabucan Mandurriao",
    },
    {
        "id": "mandurriao - 8",
        "y": 10.708439,
        "x": 122.519555,
        "name": "Iloilo Circumferential Rd 1",
    },
    {
        "id": "mandurriao - 9",
        "y": 10.740812,
        "x": 122.516723,
        "name": "Mandurriao-Sn Miguel Rd",
    },
    {
        "id": "mandurriao - 10",
        "y": 10.737323,
        "x": 122.514159,
        "name": "Iloilo Circumferential Rd 1 - Mandurriao-Sn Miguel Rd",
    },
    {
        "id": "mandurriao - 11",
        "y": 10.742752,
        "x": 122.519877,
        "name": "Mandurriao-Sn Miguel Rd - Iloilo Circumferential Rd 1",
    },
    {
        "id": "mandurriao - 12",
        "y": 10.740318,
        "x": 122.517041,
        "name": "Iloilo Circumferential Rd 1",
    },
    # JARO
    {"id": "jaro - 1", "y": 10.715677, "x": 122.562659, "name": "E Lopez St - Luna St"},
    {
        "id": "jaro - 2",
        "y": 10.717382,
        "x": 122.565081,
        "name": "Commission Civil St - Burgos St",
    },
    {"id": "jaro - 3", "y": 10.719120, "x": 122.566883, "name": "Jereos St"},
    {
        "id": "jaro - 4",
        "y": 10.723266,
        "x": 122.557606,
        "name": "Plaza Rizal St - E Lopez St",
    },
    {
        "id": "jaro - 5",
        "y": 10.724010,
        "x": 122.558338,
        "name": "Plaza Rizal St - Commission Civil St",
    },
    {
        "id": "jaro - 6",
        "y": 10.725553,
        "x": 122.557098,
        "name": "Plaza Rizal St - Iloilo-Capiz Rd/Lopez Jaena St",
    },
    {
        "id": "jaro - 7",
        "y": 10.724435,
        "x": 122.556176,
        "name": "Plaza Rizal St - El 98 St",
    },
    {
        "id": "jaro - 8",
        "y": 10.727475,
        "x": 122.555634,
        "name": "Iloilo-Capiz Rd - Lopez Jaena St",
    },
    {
        "id": "jaro - 9",
        "y": 10.730180,
        "x": 122.559115,
        "name": "Iloilo-Capiz Rd - Balabago Rd",
    },
    {
        "id": "jaro - 10",
        "y": 10.740585,
        "x": 122.582498,
        "name": "Balabago Rd - Iloilo Circumferential Rd 1",
    },
    {
        "id": "jaro - 11",
        "y": 10.740566,
        "x": 122.582805,
        "name": "Iloilo Circumferential Rd 1 - Monfort Blvd",
    },
    {"id": "jaro - 12", "y": 10.749622, "x": 122.571865, "name": "Buhang Flyover"},
    {"id": "jaro - 13", "y": 10.750644, "x": 122.568030, "name": "Buhang Flyover"},
    {
        "id": "jaro - 14",
        "y": 10.749916,
        "x": 122.569760,
        "name": "Iloilo-Capiz Rd - Iloilo Circumferential Rd 1",
    },
    {
        "id": "jaro - 15",
        "y": 10.753597,
        "x": 122.559114,
        "name": "Iloilo Circumferential Rd 1 - Iloilo Radial By-Pass Rd 4",
    },
    {
        "id": "jaro - 16",
        "y": 10.743941,
        "x": 122.539561,
        "name": "Old Lopez Jaena St - Old Iloilo-Capiz Rd",
    },
    {
        "id": "jaro - 17",
        "y": 10.742156,
        "x": 122.539263,
        "name": "Iloilo-Capiz Rd - Old Iloilo-Capiz Rd",
    },
    {
        "id": "jaro - 18",
        "y": 10.741662,
        "x": 122.540144,
        "name": "Old Lopez Jaena St - Iloilo-Capiz Rd",
    },
    {"id": "jaro - 19", "y": 10.729156, "x": 122.579585, "name": "Monfort Blvd"},
    {
        "id": "jaro - 20",
        "y": 10.765329,
        "x": 122.596838,
        "name": "Coastal Rd - Leganes",
    },
    {
        "id": "jaro - 21",
        "y": 10.776338,
        "x": 122.584777,
        "name": "Iloilo R4 Rd - Leganes",
    },
    {
        "id": "jaro - 22",
        "y": 10.782099,
        "x": 122.573353,
        "name": "Iloilo Radial By-Pass Rd 4 - Leganes",
    },
    {
        "id": "jaro - 23",
        "y": 10.750579,
        "x": 122.540739,
        "name": "Iloilo Circumferential Rd 1 - Pavia",
    },
    {
        "id": "jaro - 24",
        "y": 10.749019,
        "x": 122.539001,
        "name": "Old Iloilo-Capiz Rd - Pavia",
    },
    {   "id": "jaro - 25",
        "y": 10.720615,
        "x": 122.565701,
        "name": "Jereos St"
    },
    # LAPAZ
    {
        "id": "lapaz - 1",
        "y": 10.707804,
        "x": 122.567107,
        "name": "Luna St - Huervana St",
    },
    {   "id": "lapaz - 2", 
        "y": 10.708378, 
        "x": 122.567858, 
        "name": "Rizal St - Luna St"
     },
    {   "id": "lapaz - 3", 
        "y": 10.709233,
        "x": 122.566694,
        "name": "Luna St - Luna St"
     },
    {
        "id": "lapaz - 4",
        "y": 10.710460,
        "x": 122.570379,
        "name": "Huervana St - Burgos St",
    },
    {
        "id": "lapaz - 5",
        "y": 10.711606,
        "x": 122.571909,
        "name": "Huervana St - Jereos St",
    },
    {
        "id": "lapaz - 6",
        "y": 10.713029,
        "x": 122.570879,
        "name": "Jereos St - Huervana Ext",
    },
    {
        "id": "lapaz - 7",
        "y": 10.711777,
        "x": 122.569511,
        "name": "Huervana Ext - Burgos St",
    },
    {
        "id": "lapaz - 8",
        "y": 10.714306,
        "x": 122.575493,
        "name": "Lopez Jaena St - Baldoza St",
    },
    {
        "id": "lapaz - 9",
        "y": 10.713908,
        "x": 122.581449,
        "name": "Baldoza St - Monfort Blvd",
    },
    {
        "id": "lapaz - 10",
        "y": 10.706364,
        "x": 122.567494,
        "name": "Luna St - Taytay Forbes",
    },
    # LAPUZ
    {
        "id": "lapuz - 1",
        "y": 10.707280,
        "x": 122.571572,
        "name": "Divinagracia St - Railroad St",
    },
    {
        "id": "lapuz - 2",
        "y": 10.702261,
        "x": 122.571473,
        "name": "Rizal St - Quirino-Lopez Bridge",
    },
    {
        "id": "lapuz - 3",
        "y": 10.703187,
        "x": 122.573986,
        "name": "Railroad St - Abanilla St",
    },
    {
        "id": "lapuz - 4",
        "y": 10.701775,
        "x": 122.576817,
        "name": "Rizal St - New Iloilo Ferry Terminal Access Rd",
    },
    {
        "id": "lapuz - 5",
        "y": 10.697452,
        "x": 122.574277,
        "name": "New Iloilo Ferry Terminal Access Rd",
    },
    {
        "id": "lapuz - 6",
        "y": 10.698581,
        "x": 122.582093,
        "name": "Rizal St - Lapuz-Mansaya-Roboc Rd",
    },
    {
        "id": "lapuz - 7",
        "y": 10.706000,
        "x": 122.588709,
        "name": "Lapuz-Mansaya-Roboc Rd - Coastal Rd",
    },
    {
        "id": "lapuz - 8",
        "y": 10.697268,
        "x": 122.583455,
        "name": "Lapuz-Mansaya-Roboc Rd",
    },
]

# --- MASTER ROADS ---
# Consolidated list of road segments
roads = [
    # Arevalo Internal
    {
        "A": "villa - 1",
        "B": "villa - 6",
        "distance": 2000,
        "lanes": 2,
        "oneway": False,
        "name": "Osmena St",
        "speed": 40,
    },
    {
        "A": "villa - 1",
        "B": "villa - 4",
        "distance": 200,
        "lanes": 2,
        "oneway": False,
        "name": "Yulo Dr",
        "speed": 40,
    },
    {
        "A": "villa - 3",
        "B": "villa - 4",
        "distance": 1100,
        "lanes": 2,
        "oneway": False,
        "name": "Quezon St",
        "speed": 40,
    },
    {
        "A": "villa - 1",
        "B": "villa - 2",
        "distance": 500,
        "lanes": 2,
        "oneway": False,
        "name": "Jocson St",
        "speed": 40,
    },
    {
        "A": "villa - 2",
        "B": "villa - 3",
        "distance": 650,
        "lanes": 2,
        "oneway": False,
        "name": "Circumferential Rd 1",
        "speed": 40,
    },
    {
        "A": "villa - 7",
        "B": "villa - 6",
        "distance": 120,
        "lanes": 1,
        "oneway": False,
        "name": "Pakiad Rd",
        "speed": 40,
    },
    {
        "A": "villa - 2",
        "B": "mandurriao - 8",
        "distance": 2400,
        "lanes": 2,
        "oneway": False,
        "name": "Iloilo Circumferential Rd 1",
        "speed": 70,
    },
    # Molo Internal & District Connections
    {
        "A": "Molo - 3",
        "B": "villa - 3",
        "distance": 2100,
        "lanes": 2,
        "oneway": False,
        "name": "Molo - Arevalo Connect",
        "speed": 40,
    },
    {
        "A": "Molo - 3",
        "B": "Molo - 4",
        "distance": 190,
        "lanes": 2,
        "oneway": False,
        "name": "Locsin St",
        "speed": 40,
    },
    {
        "A": "Molo - 4",
        "B": "Molo - 5",
        "distance": 220,
        "lanes": 2,
        "oneway": False,
        "name": "Locsin St",
        "speed": 40,
    },
    {
        "A": "Molo - 4",
        "B": "Molo - 9",
        "distance": 650,
        "lanes": 2,
        "oneway": False,
        "name": "M.H Del Pilar",
        "speed": 40,
    },
    {
        "A": "Molo - 5",
        "B": "Molo - 6",
        "distance": 500,
        "lanes": 2,
        "oneway": False,
        "name": "Locsin St",
        "speed": 40,
    },
    {
        "A": "Molo - 7",
        "B": "Molo - 8",
        "distance": 16,
        "lanes": 2,
        "oneway": True,
        "name": "Rotunda",
        "speed": 40,
    },
    {
        "A": "Molo - 8",
        "B": "Molo - 3",
        "distance": 700,
        "lanes": 4,
        "oneway": True,
        "name": "San Marcos St",
        "speed": 40,
    },
    {
        "A": "Molo - 8",
        "B": "Molo - 9",
        "distance": 42,
        "lanes": 1,
        "oneway": True,
        "name": "M.H Del Pilar",
        "speed": 40,
    },
    {
        "A": "Molo - 9",
        "B": "Molo - 10",
        "distance": 20,
        "lanes": 4,
        "oneway": True,
        "name": "M.H Del Pilar",
        "speed": 40,
    },
    {
        "A": "Molo - 10",
        "B": "Proper - 1",
        "distance": 500,
        "lanes": 2,
        "oneway": True,
        "name": "Molo - Proper Connect",
        "speed": 40,
    },
    {
        "A": "Molo - 10",
        "B": "Molo - 7",
        "distance": 38,
        "lanes": 1,
        "oneway": True,
        "name": "M.H Del Pilar",
        "speed": 40,
    },
    {
        "A": "Proper - 1",
        "B": "Molo - 7",
        "distance": 550,
        "lanes": 4,
        "oneway": True,
        "name": "Gen Luna - Molo Connect",
        "speed": 40,
    },
    {
        "A": "Molo - 6",
        "B": "villa - 5",
        "distance": 6600,
        "lanes": 2,
        "oneway": False,
        "name": "Molo Blvd",
        "speed": 40,
    },
    {
        "A": "Molo - 5",
        "B": "Proper - 2",
        "distance": 1100,
        "lanes": 2,
        "oneway": False,
        "name": "Timawa St",
        "speed": 40,
    },
    {
        "A": "Molo - 6",
        "B": "Proper - 4",
        "distance": 650,
        "lanes": 2,
        "oneway": False,
        "name": "Molo Blvd 2",
        "speed": 40,
    },
    {
        "A": "Molo - 3",
        "B": "mandurriao - 6",
        "distance": 800,
        "lanes": 1,
        "oneway": False,
        "name": "New Carpenter Bridge",
        "speed": 40,
    },
    # City Proper Internal
    {
        "A": "Proper - 1",
        "B": "Proper - 2",
        "distance": 350,
        "lanes": 2,
        "oneway": False,
        "name": "Infante St 1",
        "speed": 40,
    },
    {
        "A": "Proper - 2",
        "B": "Proper - 3",
        "distance": 230,
        "lanes": 2,
        "oneway": False,
        "name": "Infante St 2",
        "speed": 40,
    },
    {
        "A": "Proper - 3",
        "B": "Proper - 4",
        "distance": 190,
        "lanes": 2,
        "oneway": True,
        "name": "Infante St 3",
        "speed": 40,
    },
    {
        "A": "Proper - 4",
        "B": "Proper - 5",
        "distance": 180,
        "lanes": 2,
        "oneway": True,
        "name": "Baluarte - Oton Blvd",
        "speed": 40,
    },
    {
        "A": "Proper - 5",
        "B": "Proper - 3",
        "distance": 190,
        "lanes": 2,
        "oneway": True,
        "name": "Rizal St 1",
        "speed": 40,
    },
    {
        "A": "Proper - 5",
        "B": "Proper - 6",
        "distance": 260,
        "lanes": 2,
        "oneway": False,
        "name": "Rizal St 2",
        "speed": 40,
    },
    {
        "A": "Proper - 6",
        "B": "Proper - 14",
        "distance": 1700,
        "lanes": 2,
        "oneway": False,
        "name": "Rizal St 3",
        "speed": 40,
    },
    {
        "A": "Proper - 6",
        "B": "Proper - 11",
        "distance": 1160,
        "lanes": 2,
        "oneway": False,
        "name": "Ledesma St",
        "speed": 40,
    },
    {
        "A": "Proper - 1",
        "B": "Proper - 7",
        "distance": 1550,
        "lanes": 2,
        "oneway": False,
        "name": "Gen Luna St 1",
        "speed": 40,
    },
    {
        "A": "Proper - 7",
        "B": "Proper - 8",
        "distance": 95,
        "lanes": 2,
        "oneway": False,
        "name": "Gen Luna St 2",
        "speed": 40,
    },
    {
        "A": "Proper - 8",
        "B": "Proper - 9",
        "distance": 75,
        "lanes": 12,
        "oneway": False,
        "name": "Gen Luna St 3",
        "speed": 40,
    },
    {
        "A": "Proper - 8",
        "B": "Proper - 10",
        "distance": 400,
        "lanes": 2,
        "oneway": True,
        "name": "Ruperto Montinola St 1",
        "speed": 40,
    },
    {
        "A": "Proper - 10",
        "B": "Proper - 11",
        "distance": 130,
        "lanes": 2,
        "oneway": True,
        "name": "Ruperto Montinola St 2",
        "speed": 40,
    },
    {
        "A": "Proper - 2",
        "B": "Proper - 10",
        "distance": 1550,
        "lanes": 2,
        "oneway": False,
        "name": "Delgado St",
        "speed": 40,
    },
    {
        "A": "Proper - 12",
        "B": "Proper - 23",
        "distance": 200,
        "lanes": 1,
        "oneway": False,
        "name": "Arroyo St",
        "speed": 40,
    },
    {
        "A": "Proper - 11",
        "B": "Proper - 13",
        "distance": 600,
        "lanes": 2,
        "oneway": True,
        "name": "JM Basa St 1",
        "speed": 40,
    },
    {
        "A": "Proper - 13",
        "B": "Proper - 14",
        "distance": 150,
        "lanes": 2,
        "oneway": False,
        "name": "JM Basa St 2",
        "speed": 40,
    },
    {
        "A": "Proper - 14",
        "B": "Proper - 15",
        "distance": 350,
        "lanes": 2,
        "oneway": False,
        "name": "General Hughes St 1",
        "speed": 40,
    },
    {
        "A": "Proper - 15",
        "B": "Proper - 16",
        "distance": 550,
        "lanes": 1,
        "oneway": False,
        "name": "Duran St",
        "speed": 40,
    },
    {
        "A": "Proper - 15",
        "B": "Proper - 22",
        "distance": 350,
        "lanes": 2,
        "oneway": False,
        "name": "General Hughes St 2",
        "speed": 40,
    },
    {
        "A": "Proper - 13",
        "B": "Proper - 17",
        "distance": 650,
        "lanes": 1,
        "oneway": False,
        "name": "Dela Rama St 1",
        "speed": 40,
    },
    {
        "A": "Proper - 17",
        "B": "Proper - 20",
        "distance": 170,
        "lanes": 1,
        "oneway": False,
        "name": "Dela Rama St 2",
        "speed": 40,
    },
    {
        "A": "Proper - 17",
        "B": "Proper - 18",
        "distance": 160,
        "lanes": 1,
        "oneway": False,
        "name": "Blumentritt 1",
        "speed": 40,
    },
    {
        "A": "Proper - 17",
        "B": "Proper - 19",
        "distance": 220,
        "lanes": 1,
        "oneway": False,
        "name": "Blumentritt 2",
        "speed": 40,
    },
    {
        "A": "Proper - 9",
        "B": "Proper - 12",
        "distance": 550,
        "lanes": 2,
        "oneway": False,
        "name": "Muelle Loney St 1",
        "speed": 40,
    },
    {
        "A": "Proper - 12",
        "B": "Proper - 18",
        "distance": 900,
        "lanes": 2,
        "oneway": False,
        "name": "Muelle Loney St 2",
        "speed": 40,
    },
    {
        "A": "Proper - 18",
        "B": "Proper - 19",
        "distance": 800,
        "lanes": 2,
        "oneway": False,
        "name": "Muelle Loney St 3",
        "speed": 40,
    },
    {
        "A": "Proper - 19",
        "B": "Proper - 21",
        "distance": 550,
        "lanes": 2,
        "oneway": False,
        "name": "Muelle Loney St 4",
        "speed": 40,
    },
    {
        "A": "Proper - 21",
        "B": "Proper - 22",
        "distance": 700,
        "lanes": 2,
        "oneway": False,
        "name": "Fort San Pedro Dr",
        "speed": 40,
    },
    {
        "A": "Proper - 13",
        "B": "Proper - 23",
        "distance": 600,
        "lanes": 2,
        "oneway": True,
        "name": "JM Basa St (Rev)",
        "speed": 40,
    },
    {
        "A": "Proper - 23",
        "B": "Proper - 24",
        "distance": 130,
        "lanes": 2,
        "oneway": True,
        "name": "Ruperto Montinola 2 (Rev)",
        "speed": 40,
    },
    {
        "A": "Proper - 24",
        "B": "Proper - 8",
        "distance": 400,
        "lanes": 2,
        "oneway": True,
        "name": "Ruperto Montinola 1 (Rev)",
        "speed": 40,
    },
    {
        "A": "Proper - 7",
        "B": "lapaz - 10",
        "distance": 500,
        "lanes": 2,
        "oneway": False,
        "name": "Bonifacio Drive",
        "speed": 40,
    },
    {
        "A": "Proper - 9",
        "B": "lapuz - 2",
        "distance": 200,
        "lanes": 2,
        "oneway": False,
        "name": "Quirino - Lopez Bridge",
        "speed": 40,
    },
    # MANDURRIAO
    {
        "A": "mandurriao - 3",
        "B": "mandurriao - 12",
        "distance": 3100,
        "lanes": 2,
        "oneway": False,
        "name": "Mandurriao - Sn Miguel Rd",
        "speed": 60,
    },
    {
        "A": "mandurriao - 4",
        "B": "mandurriao - 5",
        "distance": 1600,
        "lanes": 2,
        "oneway": False,
        "name": "Pakiad Rd",
        "speed": 40,
    },
    {
        "A": "mandurriao - 1",
        "B": "Proper - 1",
        "distance": 1100,
        "lanes": 2,
        "oneway": False,
        "name": "Old Iloilo - Capiz Rd",
        "speed": 60,
    },
    {
        "A": "mandurriao - 1",
        "B": "mandurriao - 2",
        "distance": 1100,
        "lanes": 2,
        "oneway": False,
        "name": "Mandurriao - Jaro Rd",
        "speed": 40,
    },
    {
        "A": "mandurriao - 2",
        "B": "mandurriao - 3",
        "distance": 290,
        "lanes": 2,
        "oneway": True,
        "name": "Mandurriao - Jaro Rd - Mandurriao - Sn Miguel Rd",
        "speed": 40,
    },
    {
        "A": "mandurriao - 3",
        "B": "mandurriao - 4",
        "distance": 350,
        "lanes": 4,
        "oneway": True,
        "name": "Mandurriao - Sn Miguel Rd - R Mapa St",
        "speed": 40,
    },
    {
        "A": "mandurriao - 4",
        "B": "mandurriao - 2",
        "distance": 170,
        "lanes": 2,
        "oneway": True,
        "name": "R Mapa St - Mandurriao - Jaro Rd",
        "speed": 40,
    },
    {
        "A": "mandurriao - 9",
        "B": "mandurriao - 12",
        "distance": 65,
        "lanes": 2,
        "oneway": False,
        "name": "Mandurriao-Sn Miguel Rd - Iloilo Circumferential Rd 1",
        "speed": 60,
    },
    {
        "A": "mandurriao - 10",
        "B": "mandurriao - 12",
        "distance": 450,
        "lanes": 2,
        "oneway": False,
        "name": "Iloilo Circumferential Rd 1 - Mandurriao-Sn Miguel Rd (1)",
        "speed": 70,
    },
    {
        "A": "mandurriao - 11",
        "B": "mandurriao - 12",
        "distance": 400,
        "lanes": 2,
        "oneway": False,
        "name": "Iloilo Circumferential Rd 1 - Mandurriao-Sn Miguel Rd (2)",
        "speed": 70,
    },
    {
        "A": "mandurriao - 4",
        "B": "mandurriao - 6",
        "distance": 1600,
        "lanes": 2,
        "oneway": False,
        "name": "R Mapa St",
        "speed": 40,
    },
    {
        "A": "mandurriao - 6",
        "B": "mandurriao - 7",
        "distance": 200,
        "lanes": 1,
        "oneway": False,
        "name": "R Mapa St - Extension",
        "speed": 40,
    },
    # JARO
    {
        "A": "jaro - 11",
        "B": "jaro - 20",
        "distance": 3200,
        "lanes": 2,
        "oneway": False,
        "name": "Monfort Blvd - Leganes",
        "speed": 70,
    },
    {
        "A": "jaro - 19",
        "B": "jaro - 11",
        "distance": 1300,
        "lanes": 2,
        "oneway": False,
        "name": "Lapaz - Monfort Blvd",
        "speed": 70,
    },
    {
        "A": "jaro - 15",
        "B": "jaro - 22",
        "distance": 3500,
        "lanes": 2,
        "oneway": False,
        "name": "Iloilo Circumferential - Iloilo Radial By-Pass Rd 4",
        "speed": 70,
    },
    {
        "A": "jaro - 15",
        "B": "jaro - 13",
        "distance": 1100,
        "lanes": 2,
        "oneway": False,
        "name": "Iloilo Radial By-Pass Rd 4 - Buhang Flyover",
        "speed": 70,
    },
    {
        "A": "jaro - 13",
        "B": "jaro - 14",
        "distance": 190,
        "lanes": 1,
        "oneway": False,
        "name": "Buhang Flyover - Iloilo-Capiz Rd",
        "speed": 40,
    },
    {
        "A": "jaro - 14",
        "B": "jaro - 12",
        "distance": 220,
        "lanes": 1,
        "oneway": False,
        "name": "Iloilo-Capiz Rd - Buhang Flyover",
        "speed": 40,
    },
    {
        "A": "jaro - 12",
        "B": "jaro - 10",
        "distance": 1600,
        "lanes": 2,
        "oneway": False,
        "name": "Buhang Flyover - Balabago Rd",
        "speed": 70,
    },
    {
        "A": "jaro - 10",
        "B": "jaro - 11",
        "distance": 35,
        "lanes": 1,
        "oneway": False,
        "name": "Iloilo-Capiz Rd - Iloilo Circumferential Rd 1 - Monfort Blvd",
        "speed": 70,
    },
    {
        "A": "jaro - 17",
        "B": "mandurriao - 1",
        "distance": 3100,
        "lanes": 4,
        "oneway": False,
        "name": "Old Iloilo-Capiz Rd - Old Lopez Jaena St",
        "speed": 60,
    },
    {
        "A": "jaro - 17",
        "B": "jaro - 16",
        "distance": 210,
        "lanes": 4,
        "oneway": False,
        "name": "Old Iloilo-Capiz Rd - Old Lopez Jaena St",
        "speed": 60,
    },
    {
        "A": "jaro - 16",
        "B": "jaro - 24",
        "distance": 550,
        "lanes": 4,
        "oneway": False,
        "name": "Old Iloilo-Capiz Rd - Pavia",
        "speed": 70,
    },
    {
        "A": "jaro - 14",
        "B": "jaro - 21",
        "distance": 3300,
        "lanes": 2,
        "oneway": False,
        "name": "Iloilo-Capiz Rd - Iloilo Circumferential Rd 1",
        "speed": 60,
    },
    {
        "A": "jaro - 15",
        "B": "jaro - 23",
        "distance": 3500,
        "lanes": 2,
        "oneway": False,
        "name": "Iloilo Radial By-Pass Rd 4",
        "speed": 70,
    },
    {
        "A": "jaro - 14",
        "B": "jaro - 9",
        "distance": 2600,
        "lanes": 2,
        "oneway": False,
        "name": "Iloilo Capiz Rd - Balabago Rd",
        "speed": 40,
    },
    {
        "A": "jaro - 12",
        "B": "jaro - 13",
        "distance": 450,
        "lanes": 1,
        "oneway": False,
        "name": "Buhang Flyover",
        "speed": 40,
    },
    {
        "A": "jaro - 9",
        "B": "jaro - 10",
        "distance": 2900,
        "lanes": 2,
        "oneway": False,
        "name": "Balabago Rd",
        "speed": 40,
    },
    {
        "A": "jaro - 3",
        "B": "jaro - 25",
        "distance": 210,
        "lanes": 1,
        "oneway": False,
        "name": "Jereos St",
        "speed": 40,
    },
    {
        "A": "jaro - 2",
        "B": "jaro - 5",
        "distance": 1000,
        "lanes": 1,
        "oneway": False,
        "name": "Commission Civil St",
        "speed": 40,
    },
    {
        "A": "jaro - 1",
        "B": "jaro - 4",
        "distance": 1000,
        "lanes": 2,
        "oneway": False,
        "name": "E Lopez St",
        "speed": 40,
    },
    {
        "A": "jaro - 6",
        "B": "jaro - 9",
        "distance": 550,
        "lanes": 1,
        "oneway": True,
        "name": "Plaza Rizal St - Balabago Rd",
        "speed": 40,
    },
    {
        "A": "jaro - 9",
        "B": "jaro - 8",
        "distance": 500,
        "lanes": 2,
        "oneway": True,
        "name": "Iloilo-Capiz Rd - Lopez Jaena St",
        "speed": 40,
    },
    {
        "A": "jaro - 8",
        "B": "jaro - 6",
        "distance": 260,
        "lanes": 3,
        "oneway": True,
        "name": "Lopez Jaena St - Plaza Rizal St",
        "speed": 40,
    },
    {
        "A": "jaro - 8",
        "B": "jaro - 18",
        "distance": 2300,
        "lanes": 1,
        "oneway": False,
        "name": "Lopez Jaena St - Old Lopez Jaena St",
        "speed": 40,
    },
    {
        "A": "jaro - 18",
        "B": "jaro - 17",
        "distance": 100,
        "lanes": 2,
        "oneway": False,
        "name": "Old Lopez Jaena St - Old Iloilo-Capiz Rd",
        "speed": 40,
    },
    {
        "A": "jaro - 18",
        "B": "jaro - 16",
        "distance": 270,
        "lanes": 2,
        "oneway": True,
        "name": "Old Lopez Jaena St - Old Iloilo-Capiz Rd",
        "speed": 40,
    },
    {
        "A": "jaro - 7",
        "B": "jaro - 4",
        "distance": 190,
        "lanes": 4,
        "oneway": True,
        "name": "El 98 St - Plaza Rizal St - E Lopez St",
        "speed": 40,
    },
    {
        "A": "jaro - 4",
        "B": "jaro - 5",
        "distance": 120,
        "lanes": 4,
        "oneway": True,
        "name": "E Lopez St - Plaza Rizal St - Commission Civil St",
        "speed": 40,
    },
    {
        "A": "jaro - 5",
        "B": "jaro - 6",
        "distance": 230,
        "lanes": 4,
        "oneway": True,
        "name": "Commission Civil St - Plaza Rizal St - Iloilo-Capiz Rd",
        "speed": 40,
    },
    {
        "A": "jaro - 6",
        "B": "jaro - 7",
        "distance": 160,
        "lanes": 5,
        "oneway": True,
        "name": "Iloilo-Capiz Rd - Plaza Rizal St - El 98 St",
        "speed": 40,
    },
    {
        "A": "jaro - 7",
        "B": "mandurriao - 1",
        "distance": 700,
        "lanes": 2,
        "oneway": False,
        "name": "El 98 St",
        "speed": 40,
    },
    # LAPAZ
    {
        "A": "lapaz - 3",
        "B": "jaro - 1",
        "distance": 800,
        "lanes": 2,
        "oneway": False,
        "name": "Luna St",
        "speed": 40,
    },
    {
        "A": "lapaz - 3",
        "B": "lapaz - 1",
        "distance": 170,
        "lanes": 2,
        "oneway": False,
        "name": "Luna St - Huervana St",
        "speed": 40,
    },
    {
        "A": "lapaz - 1",
        "B": "lapaz - 10",
        "distance": 160,
        "lanes": 2,
        "oneway": False,
        "name": "Luna St - Esplanade 5",
        "speed": 40,
    },
    {
        "A": "lapaz - 2",
        "B": "lapaz - 3",
        "distance": 160,
        "lanes": 4,
        "oneway": True,
        "name": "Rizal St - Luna St",
        "speed": 40,
    },
    {
        "A": "lapaz - 1",
        "B": "lapaz - 2",
        "distance": 110,
        "lanes": 4,
        "oneway": True,
        "name": "Huervana St - Rizal St",
        "speed": 40,
    },
    {
        "A": "lapaz - 2",
        "B": "lapaz - 4",
        "distance": 350,
        "lanes": 2,
        "oneway": False,
        "name": "Huervana St - Burgos St",
        "speed": 40,
    },
    {
        "A": "lapaz - 4",
        "B": "lapaz - 5",
        "distance": 210,
        "lanes": 4,
        "oneway": True,
        "name": "Huervana St - Jereos St",
        "speed": 40,
    },
    {
        "A": "lapaz - 5",
        "B": "lapaz - 6",
        "distance": 200,
        "lanes": 4,
        "oneway": True,
        "name": "Jereos St - Huervana Ext",
        "speed": 40,
    },
    {
        "A": "lapaz - 6",
        "B": "lapaz - 7",
        "distance": 210,
        "lanes": 3,
        "oneway": True,
        "name": "Huervana Ext",
        "speed": 40,
    },
    {
        "A": "lapaz - 7",
        "B": "lapaz - 4",
        "distance": 180,
        "lanes": 4,
        "oneway": True,
        "name": "Burgos St - Huervana St",
        "speed": 40,
    },
    {
        "A": "lapaz - 5",
        "B": "lapaz - 8",
        "distance": 500,
        "lanes": 2,
        "oneway": False,
        "name": "Lopez Jaena St",
        "speed": 40,
    },
    {
        "A": "lapaz - 8",
        "B": "lapaz - 9",
        "distance": 650,
        "lanes": 2,
        "oneway": False,
        "name": "Baldoza St",
        "speed": 40,
    },
    {
        "A": "lapaz - 9",
        "B": "lapuz - 7",
        "distance": 1200,
        "lanes": 2,
        "oneway": False,
        "name": "Coastal Rd",
        "speed": 70,
    },
    {
        "A": "lapaz - 9",
        "B": "jaro - 19",
        "distance": 1800,
        "lanes": 2,
        "oneway": False,
        "name": "Monfort Blvd",
        "speed": 70,
    },
    {
        "A": "lapaz - 7",
        "B": "jaro - 2",
        "distance": 850,
        "lanes": 1,
        "oneway": False,
        "name": "Burgos St",
        "speed": 40,
    },
    {
        "A": "lapaz - 6",
        "B": "jaro - 3",
        "distance": 600,
        "lanes": 1,
        "oneway": False,
        "name": "Jereos St",
        "speed": 40,
    },
    {
        "A": "lapaz - 4",
        "B": "lapuz - 1",
        "distance": 450,
        "lanes": 1,
        "oneway": False,
        "name": "Divinagracia St",
        "speed": 40,
    },
    {
        "A": "lapuz - 1",
        "B": "lapuz - 3",
        "distance": 550,
        "lanes": 1,
        "oneway": False,
        "name": "Railroad St",
        "speed": 40,
    },
    {
        "A": "lapaz - 2",
        "B": "lapuz - 2",
        "distance": 850,
        "lanes": 2,
        "oneway": False,
        "name": "Rizal St - Huervana St",
        "speed": 40,
    },
    {
        "A": "lapuz - 2",
        "B": "lapuz - 4",
        "distance": 600,
        "lanes": 2,
        "oneway": False,
        "name": "Rizal St - Ferry Terminal Access Rd",
        "speed": 40,
    },
    {
        "A": "lapuz - 4",
        "B": "lapuz - 5",
        "distance": 600,
        "lanes": 3,
        "oneway": False,
        "name": "New Iloilo Ferry Terminal Access Rd",
        "speed": 40,
    },
    {
        "A": "lapuz - 4",
        "B": "lapuz - 6",
        "distance": 700,
        "lanes": 2,
        "oneway": False,
        "name": "Rizal St - Iloilo Airport Direct Rd",
        "speed": 40,
    },
    {
        "A": "lapuz - 6",
        "B": "lapuz - 7",
        "distance": 1100,
        "lanes": 2,
        "oneway": False,
        "name": "Lapuz Mansaya Loboc Rd",
        "speed": 40,
    },
    {
        "A": "lapuz - 6",
        "B": "lapuz - 8",
        "distance": 240,
        "lanes": 1,
        "oneway": False,
        "name": "Iloilo Airport Direct Rd",
        "speed": 40,
    },
]


